name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  BYOND_MAJOR: "512"
  BYOND_MINOR: "1485"
  SPACEMAN_DMM_VERSION: suite-1.5

jobs:

  Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Configure Environment
        run:  chmod -R +x ./tools/travis
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          BASENAME: polaris
          TEST_DEFINE: UNIT_TEST
          TEST_FILE: code/_unit_tests.dm
          RUN: 1wond
        run: ldd librust_g.so && tools/travis/compile_and_run.sh

  Maps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Configure Environment
        run:  chmod -R +x ./tools/travis
      - name: Run Tests
        env: 
          TEST_DEFINE: MAP_TEST
          TEST_FILE: code/_map_tests.dm
          RUN: 0
        run: ldd librust_g.so && tools/travis/compile_and_run.sh

  Awaysites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Configure Environment
        run:  chmod -R +x ./tools/travis
      - name: Run Tests
        env: 
          TEST_DEFINE: AWAY_MISSION_TEST
          TEST_FILE: code/_away_mission_tests.dm
          RUN: 0
        run: ldd librust_g.so && tools/travis/compile_and_run.sh